var annotated_dup =
[
    [ "applet_args_v4_t", "structapplet__args__v4__t.html", "structapplet__args__v4__t" ],
    [ "critical_section_s", "structcritical__section__s.html", "structcritical__section__s" ],
    [ "datetime_t", "structdatetime__t.html", "structdatetime__t" ],
    [ "event_s", "structevent__s.html", "structevent__s" ],
    [ "find_context_t", "structfind__context__t.html", "structfind__context__t" ],
    [ "fs_stat_t", "structfs__stat__t.html", "structfs__stat__t" ],
    [ "key_press_event_config_t", "structkey__press__event__config__t.html", "structkey__press__event__config__t" ],
    [ "lcd_cursor_s", "structlcd__cursor__s.html", "structlcd__cursor__s" ],
    [ "lcd_draw_s", "structlcd__draw__s.html", "structlcd__draw__s" ],
    [ "lcd_font_s", "structlcd__font__s.html", "structlcd__font__s" ],
    [ "lcd_lock_s", "structlcd__lock__s.html", "structlcd__lock__s" ],
    [ "lcd_s", "structlcd__s.html", "structlcd__s" ],
    [ "lcd_surface_s", "structlcd__surface__s.html", "structlcd__surface__s" ],
    [ "lcd_thread_safe_s", "structlcd__thread__safe__s.html", "structlcd__thread__safe__s" ],
    [ "message_queue_nonatomic_t", "structmessage__queue__nonatomic__t.html", "structmessage__queue__nonatomic__t" ],
    [ "message_queue_s", "structmessage__queue__s.html", "structmessage__queue__s" ],
    [ "nand_params_t", "structnand__params__t.html", "structnand__params__t" ],
    [ "semaphore_s", "structsemaphore__s.html", "structsemaphore__s" ],
    [ "thread_s", "structthread__s.html", "structthread__s" ],
    [ "threading_waitable_t", "structthreading__waitable__t.html", "structthreading__waitable__t" ],
    [ "ui_button_s", "structui__button__s.html", "structui__button__s" ],
    [ "ui_component_s", "structui__component__s.html", "structui__component__s" ],
    [ "ui_event_s", "structui__event__s.html", "structui__event__s" ],
    [ "ui_message_s", "structui__message__s.html", "structui__message__s" ],
    [ "ui_rect_s", "structui__rect__s.html", "structui__rect__s" ]
];